/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "Button_aliases.h"
#include "Button.h"
#include "LED_aliases.h"
#include "LED.h"
#include "RPWM.h"
#include "Clock_1.h"
#include "R_PWM_aliases.h"
#include "R_PWM.h"
#include "L_PWM_aliases.h"
#include "L_PWM.h"
#include "LPWM.h"
#include "EN_L_aliases.h"
#include "EN_L.h"
#include "EN_R_aliases.h"
#include "EN_R.h"
#include "UART.h"
#include "SDA_aliases.h"
#include "SDA.h"
#include "SCL_aliases.h"
#include "SCL.h"
#include "I2C.h"
#include "I2C_PVT.h"
#include "Timer1.h"
#include "isr.h"
#include "UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

